version: '2'
services:
  alice.es-test:
    image: elasticsearch:latest
    container_name: es.test
    restart: on-failure
    # network_mode: host
    working_dir: /data/elasticsearch
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xms1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 2g
    cap_add:
      - IPC_LOCK
    volumes:
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - /data/es.test.test/data:/usr/share/elasticsearch/data
      - /data/es.test.test/logs:/usr/share/elasticsearch/logs
    ports:
      - 9800:7800
      - 9801:7801
    # networks:
    #   - esnet

  alice.es-test1:
    image: elasticsearch:latest
    container_name: es.test1
    restart: on-failure
    # network_mode: host
    working_dir: /data/elasticsearch
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xms1g"
      # - "discovery.zen.ping.unicast.hosts=alice.es-test"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 2g
    cap_add:
      - IPC_LOCK
    volumes:
      - ./elasticsearch1.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - /data1/es.test.test/data:/usr/share/elasticsearch/data
      - /data1/es.test.test/logs:/usr/share/elasticsearch/logs
    ports:
      - 9810:7810
      - 9811:7811
    # networks:
    #   - esnet

networks:
  esnet:
    driver: bridge
